language: ruby
rvm:
- 2.0.0-p481
env:
- DB=sqlite
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate test
deploy:
  provider: heroku
  api_key:
    secure: BBi5jzOKCbmZfgdSw5gSsaqgWm4mLjxBi1g40PbIDXLm5w7LLalrLxE7cSDpMjxsLB9jjD8Q7dJuAecF3wosF0oGxG/mjno1C/KxiiXQRv6u0wEXbYzN4y1iliM0jqVmZyyt+LbCx4fMg1OT2of60JD+SOExupLjU1mDk4QU4rw=
  app: memberbook.co.kr
  on:
    repo: dobestan/memberbook.co.kr
